-- 13
SELECT MAX(SALARY), MIN(SALARY),
AVG(SALARY)
FROM EMPLOYEE, DEPARTMENT
WHERE DNO=DNUMBER AND
DNAME='Research';


-- 14
SELECT count(*) FROM EMPLOYEE,DEPARTMENT WHERE DNO=DNUMBER AND DNAME='Research';


-- 15
select dno, AVG(salary),count(*) FROM EMPLOYEE GROUP BY dno;

-- 16
SELECT pnumber, pname, COUNT(*) FROM PROJECT, WORKS_ON WHERE PNUMBER=PNO GROUP BY pnumber, pname;

-- 17
SELECT pnumber, pname, COUNT(*) FROM PROJECT, WORKS_ON WHERE PNUMBER=PNO GROUP BY pnumber, pname HAVING COUNT(*) > 2;

-- 18
select * from EMPLOYEE where address= 'Delhi';

-- 19
SELECT NAME, PNAME
FROM DEPARTMENT, EMPLOYEE,
WORKS_ON, PROJECT
WHERE DNUMBER=DNO AND SSN=ESSN
AND PNO=PNUMBER
ORDER BY NAME;
